version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "create tests environment"
          command: |
            source activate base
            conda create -n tests python=3.5
            source activate tests
            pip install -r requirements.txt

      - save_cache:
          key: v1-conda-environments-{{ checksum "requirements.txt" }}
          paths:
            - /opt/conda/envs/tests

  test:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-conda-environments-{{ checksum "requirements.txt" }}
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "test"
          command: |
            source activate tests
            python -m unittest tests/test_paf.py
            python -m unittest tests/test_samtag.py


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
